name: context-example

on:
    push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: github context
              run: echo '${{toJson(github)}}'

            - name: github ref
              run: echo '${{github.ref}}'