name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v7

        - name: Welcome message
          run: |
               echo "My first Github Actions Job"
               ls
               cat README.md
        - name: display a dragon
          run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR"