name: Generate ASCII

on: 
  workflow_dispatch:
  pull_request: 
    types: 
      - opened
      - closed

    paths-ignore: 
      - README.md
  push: 
    branches:
      - main
      - '!feature/'
    
    paths-ignore: 
      - README.md
  # schedule:
  #   - cron: '* * * * *'

env:
    app_name: My-App

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v7

            - name: install cowsay
              run: sudo apt-get install cowsay -y

            - name: display a dragon
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

            - name: sleep for 3 seconds
              run: sleep 3

            - name: upload dragon text file
              uses: actions/upload-artifact@v7
              with:
                name: dragon-text-artifact
                path: dragon.txt

            - name: use environment variable
              run: |
                echo "My App: $app_name"
                echo "My App: ${{env.app_name}}"
            
            - name: use secrets 
              run: |
                echo "Docker Password: ${{secrets.DOCKER_PASSWORD}}"

            - name: use vars
              run: echo docker username is ${{vars.DOCKER_USERNAME}}

            # - name: check weather file exist
            #   run: grep -i "dragon" dragon.txt

            # - name: read file
            #   run: cat dragon.txt

            # - name: list files
            #   run: ls

    second_job:
        if: github.ref == 'refs/heads/main'
        needs: first_job
        runs-on: ubuntu-latest
        timeout-minutes: 1
        concurrency: 
          group: deployment
          cancel-in-progress: false
        env:
            node_version: node 22
        steps:
            - name: download dragon text file
              uses: actions/download-artifact@v8
              with:
                name: dragon-text-artifact

            - name: sleep for 6 seconds
              run: sleep 6

            - name: check weather file exist
              run: grep -i "dragon" dragon.txt

            - name: use environment variables
              env:
                step: 15
              run: |
                echo "node version: $node_version"
                echo "node version: ${{env.node_version}}"
                echo "step: $step"
                echo "step: ${{env.step}}"


    third_job:
        needs: [second_job]
        runs-on: ubuntu-latest
        steps:
            - name: download dragon text file
              uses: actions/download-artifact@v8
              with:
                name: dragon-text-artifact

            - name: read file
              run: cat dragon.txt

            - name: deploy 
              run: echo "deploying..."

            - name: use environment variable
              run: |
                echo "My App: $app_name"
                echo "My App: ${{env.app_name}}"