name: Generate ASCII

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v7

            - name: list files
              run: ls -ltra

            - name: execute shell script
              run: ./ascii-script.sh