name: Generate ASCII

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v7

            - name: install cowsay
              run: sudo apt-get install cowsay -y

            - name: display a dragon
              run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt

            - name: sleep for 30 seconds
              run: sleep 30

            # - name: check weather file exist
            #   run: grep -i "dragon" dragon.txt

            # - name: read file
            #   run: cat dragon.txt

            # - name: list files
            #   run: ls

    second_job:
        runs-on: ubuntu-latest
        steps:
            - name: sleep for 10 seconds
              run: sleep 10

            - name: check weather file exist
              run: grep -i "dragon" dragon.txtt

    third_job:
        runs-on: ubuntu-latest
        steps:
            - name: read file
              run: cat dragon.txt

            - name: deploy 
              run: echo "deploying..."